article/urls.py
from django.urls import path

from . import views

app_name = "article"

urlpatterns = [
    path('', views.article_list, name="article_list"),
    path('detail/<int:pk>/', views.article_detail, name="article_detail"),
]

gallery/urls.py
from django.urls import path

from . import views

app_name = "gallery"

urlpatterns = [
    path('', views.illust_list, name="illust_list"),
    path('detail/<int:pk>/', views.illust_detail, name="illust_detail"),
    path('comment/<int:pk>/', views.illust_comment_create, name="illust_comment")
]

pages/urls.py
from django.urls import path

from . import views

app_name = "pages"

urlpatterns = [
    path('', views.top, name="top"),
    path('users/detail', views.user_detail, name="user_detail"),
    path('design_policy', views.DesignPolicy.as_view(), name="design_policy"),
    path('variable', views.variable, name="variable"),
]

templates/extends/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script
      async
      src="https://www.googletagmanager.com/gtag/js?id=G-3WT8DJKJ66"
    ></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag() {
        dataLayer.push(arguments);
      }
      gtag("js", new Date());

      gtag("config", "G-3WT8DJKJ66");
    </script>

    <title>Article | Nostalon</title>

    {% if description %}
    <meta name="description" content="{{ description }}" />
    {% else %}
    <meta name="description" content="Free Web tutorials" />
    {% endif %}

    <meta
      name="viewport"
      content="width=device-width,initial-scale=1.0,minimum-scale=1.0"
    />

    <!-- styles -->
    <link rel="stylesheet" href="{% static 'css/entry.css' %}" />

    <!-- scripts -->
    <script type="module" src="{% static 'js/index.js' %}"></script>

    <!-- favicon -->
    <link rel="icon" href="{% static 'global/media/NontalonLogo.png' %}" />

    <!-- Google Font references -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Anton&family=Fredericka+the+Great&family=Noto+Sans+JP:wght@400;700&family=Noto+Sans:wght@400;700&family=UnifrakturMaguntia&display=swap"
      rel="stylesheet"
    />

    <!-- Material Icons -->
    <link
      rel="stylesheet"
      href="https://fonts.sandbox.google.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
    />

    <!-- third party library -->
    <script
      src="https://kit.fontawesome.com/c226d01fbd.js"
      crossorigin="anonymous"
    ></script>

    <!-- Twitter Card -->
    {% include "includes/twitter_card.html" %}
  </head>

  <script>
    document.addEventListener("DOMContentLoaded", (e) => {
      const searchForm = document.getElementById("search-form");

      for (const tag of document.getElementsByClassName("tag")) {
        tag.addEventListener("click", () => {
          const pk = tag.dataset.pk;
          const checkbox = document.querySelector(
            `input[name="tags"][value="${pk}"]`
          );
          if (checkbox.checked) {
            checkbox.checked = false;
          } else {
            checkbox.checked = true;
          }
          searchForm.submit();
        });
      }

      for (const check of document.getElementsByName("tags")) {
        check.addEventListener("change", () => {
          searchForm.submit();
        });
      }
    });
  </script>

  <body>
    <header class="header">
      <div class="headerLogo">
        <div class="nostalonLogoWhiten --titleCharSize">
          <a class="noDecoratedLink" href="{% url 'pages:top' %}">okmtyuta</a>
        </div>
      </div>

      <ul class="rowList--grid headerUtils">
        <a
          class="underlineWhenHoverFromCenter embeddedLink"
          href="{% url 'pages:top' %}"
        >
          <li class="itemWithIcon headerMenuItem">
            <span class="material-symbols-outlined"> search </span>
            <div class="itemWithIconContent">Search</div>
          </li>
        </a>

        <a
          class="underlineWhenHoverFromCenter embeddedLink"
          href="{% url 'admin:index' %}"
        >
          <li class="itemWithIcon headerMenuItem">
            <span class="material-symbols-outlined"> person </span>
            <div class="itemWithIconContent">Log In</div>
          </li>
        </a>
      </ul>

      <ul class="rowList--grid headerMenu">
        <a
          class="underlineWhenHoverFromCenter embeddedLink"
          href="{% url 'pages:top' %}"
        >
          <li class="itemWithIcon headerMenuItem">
            <span class="material-symbols-outlined"> functions </span>
            <div class="itemWithIconContent">Math</div>
          </li>
        </a>

        <a
          class="underlineWhenHoverFromCenter embeddedLink"
          href="{% url 'gallery:illust_list' %}"
        >
          <li class="itemWithIcon headerMenuItem">
            <span class="material-symbols-outlined"> gesture </span>
            <div class="itemWithIconContent">Gallery</div>
          </li>
        </a>

        <!-- <a
          class="underlineWhenHoverFromCenter embeddedLink"
          href="{% url 'pages:top' %}"
        >
          <li class="itemWithIcon headerMenuItem">
            <span class="material-symbols-outlined"> photo </span>
            <div class="itemWithIconContent">Picture</div>
          </li>
        </a> -->

        <a
          class="underlineWhenHoverFromCenter embeddedLink"
          href="{% url 'pages:top' %}"
        >
          <li class="itemWithIcon headerMenuItem">
            <span class="material-symbols-outlined"> code </span>
            <div class="itemWithIconContent">Dev</div>
          </li>
        </a>

        <a
          class="underlineWhenHoverFromCenter embeddedLink"
          href="{% url 'article:article_list' %}"
        >
          <li class="itemWithIcon headerMenuItem">
            <span class="material-symbols-outlined"> article </span>
            <div class="itemWithIconContent">Articles</div>
          </li>
        </a>
      </ul>
    </header>

    {% block main %} {% endblock %}

    <footer class="footer">
      <div class="band-50"></div>

      <div class="forDesktopAndTablet singleFrame">
        <ul class="rowList--flex --annotationCharSize">
          <li class="footerMenuSection">
            <div class="footerMenuCategory thirdHeadlineWithLeftLine">
              More Info
            </div>
            <ul class="footerMenuList colList">
              <li class="footerMenuItem colListItem">
                <a class="embeddedLink" href="./coding_rules.html">
                  Coding Rules
                </a>
              </li>
              <li class="footerMenuItem colListItem">
                <a class="embeddedLink" href="./styling_guide.html">
                  Styling Guidelines
                </a>
              </li>
              <li class="footerMenuItem colListItem">
                <a
                  class="embeddedLink"
                  href="./nostalon_creation_exhibition.html"
                >
                  Atelier
                </a>
              </li>
              <li class="footerMenuItem colListItem">
                <a class="embeddedLink" href="./css_animation.html"> Anime </a>
              </li>
            </ul>
          </li>

          <li class="footerMenuSection">
            <div class="footerMenuCategory thirdHeadlineWithLeftLine">SNS</div>
            <ul class="footerMenuList rowList--flex">
              <li class="footerMenuItem colListItem">
                <a class="embeddedLink" href="{% url 'pages:top' %}"
                  ><i class="fa-brands fa-twitter fa-2x"></i
                ></a>
              </li>
              <li class="footerMenuItem colListItem">
                <a class="embeddedLink" href="{% url 'pages:top' %}"
                  ><i class="fa-brands fa-youtube fa-2x"></i
                ></a>
              </li>
            </ul>
          </li>
        </ul>
      </div>

      <ul class="forMobile">
        <li>
          <a class="bandLink" href="{% url 'pages:top' %}">
            <div class="bandLinkContent">To be prepared</div>
          </a>
        </li>

        <li>
          <a class="bandLink" href="{% url 'pages:top' %}">
            <div class="bandLinkContent">To be prepared</div>
          </a>
        </li>
      </ul>

      <div class="footerCopyRight">2020 - 2022 © Nostalon</div>
    </footer>
  </body>
</html>