gallery/urls.py
from django.urls import path

from . import views

app_name = "gallery"

urlpatterns = [
    path('', views.illust_list, name="illust_list"),
    path('detail/<int:pk>/', views.illust_detail, name="illust_detail"),
    path('comment/<int:pk>/', views.illust_comment_create, name="illust_comment")
]

pages/urls.py
from django.urls import path

from . import views

app_name = "pages"

urlpatterns = [
    path('', views.top, name="top"),
    path('users/detail', views.user_detail, name="user_detail"),
    path('design_policy', views.DesignPolicy.as_view(), name="design_policy"),
    path('variable', views.variable, name="variable"),
]

gallery/models.py
from django.db import models
from django.utils import timezone  # 追加


class IllustTag(models.Model):
    name = models.CharField('タグ名', max_length=100)

    def __str__(self):
        if hasattr(self, 'illust_count'):
            return f'{self.name}({self.illust_count})'
        else:
            return self.name


class Illust(models.Model):
    title = models.CharField('タイトル', max_length=100)
    illust = models.ImageField(upload_to='uploads/%Y/%m/%d/')
    caption = models.CharField('Caption', max_length=120, default="")
    author = models.CharField(max_length=255)
    description = models.TextField()
    body = models.TextField()
    illust_tags = models.ManyToManyField(IllustTag, verbose_name='タグ', blank=True)
    is_public = models.BooleanField('Public Illust?', default=True)
    is_picked_up = models.BooleanField('Picked up Article?', default=False)
    created_at = models.DateTimeField('Created at', default=timezone.now)
    updated_at = models.DateTimeField('Updated at', default=timezone.now)

    def __str__(self):
        return self.title


class IllustComment(models.Model):
    """記事に紐づくコメント"""
    name = models.CharField('名前', max_length=255, default='Anonymous')
    text = models.TextField('本文')
    target = models.ForeignKey(Illust, on_delete=models.CASCADE, verbose_name='対象記事')
    is_public = models.BooleanField('Public Comment?', default=True)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.text[:20]

gallery/forms.py
from django import forms
from django.db.models import Count
from .models import IllustTag, IllustComment
from .widgets import CustomCheckboxSelectMultiple

class IllustSearchForm(forms.Form):
    """記事検索フォーム。"""
    key_word = forms.CharField(
        label = '検索キーワード',
        required = False,
    )

    tags = forms.ModelMultipleChoiceField(
        label = 'タグでの絞り込み',
        required = False,
        queryset=IllustTag.objects.annotate(illust_count=Count('illust')).order_by('name'),  # 変更
        widget = CustomCheckboxSelectMultiple
    )
    


class IllustCommentCreateForm(forms.ModelForm):
    class Meta:
        model = IllustComment
        exclude = ('target', 'created_at', "is_public")
        widgets = {
            'text': forms.Textarea(
                attrs={'placeholder': "こちらにコメントをどうぞ"}
            )
        }

gallery/views.py
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from .models import Illust, IllustComment
from .forms import IllustSearchForm, IllustCommentCreateForm

def illust_list(request):
    template_name = "gallery/illust_list.html"

    form = IllustSearchForm(request.GET or None)
    illusts = Illust.objects.all().order_by("-created_at")
    if form.is_valid():
        tags = form.cleaned_data.get('tags')
        if tags:
            for tag in tags:
                illusts = Illust.objects.filter(illust_tags = tag)
        
        key_word = form.cleaned_data.get('key_word')
        if key_word:
            for word in key_word.split():
                illusts = Illust.objects.filter(Q(title__icontains=word) | Q(body__icontains=word) | Q(caption__icontains=word))

    picked_up_illusts = Illust.objects.filter(is_picked_up=True).order_by("-created_at")

    context = {
        "illusts": illusts,
        "picked_up_illusts": picked_up_illusts,
        "illust_search_form": form
    }
    return render(request, template_name, context)

def illust_detail(request, pk):
    template_name = "gallery/illust_detail.html"
    illust = Illust.objects.get(pk = pk)
    comments = IllustComment.objects.filter(target=illust)
    print(comments)
    context = {
        "illust": illust,
        "comments": comments,
        # "twitter_card": article,
    }
    return render(request, template_name, context)


def illust_comment_create(request, pk):
    template_name = "gallery/illust_comment_form.html"

    if request.method == "GET":
        form = IllustCommentCreateForm(request.GET or None)

    if request.method == "POST":
        illust = get_object_or_404(Illust, pk=pk)

        form = IllustCommentCreateForm(request.POST)
        comment = form.save(commit=False)
        comment.target = illust
        comment.save()
        print(form)

        return redirect("gallery:illust_detail", pk=pk)
    
    context = {
        "form": form,
        "illust": get_object_or_404(Illust, pk=pk)
    }

    return render(request, template_name, context)

gallery/templates/gallery/illust_comment_form.html
{% extends 'extends/base.html' %} {% block main %}

<div class="singleFrame">
  <form action="" method="POST" id="comment-form">
    {{ form.non_field_errors }} {% for field in form %}
    <div class="field">
      {{ field.label_tag }} {{ field }} {% if field.help_text %}
      <span class="helptext">※{{ field.help_text }}</span>
      {% endif %} {{ field.errors }}
    </div>
    {% endfor %} {% csrf_token %}

    <button type="submit" class="btn-link">送信</button>
    <a
      class="button btn-link"
      href="{% url 'gallery:illust_detail' illust.pk %}"
      >送信せずに戻る</a
    >
  </form>
</div>

{% endblock %}

gallery/templates/gallery/illust_detail.html
{% extends "extends/base.html" %} {% load static %} {% block main %}

<main class="main">
  <div class="doubleFrame">
    <div class="doubleFrame_main">
      <div class="pageTitle">{{ illust.title }}</div>

      <div class="illust">
        <div class="illust-created-at">
          {{ illust.created_at|date:"nS F, Y" }}
        </div>

        <div class="illust-list-item-illust">
          <img src="{{ illust.illust.url }}" alt="" />
        </div>

        <div class="illust-body">{{ illust.body }}</div>

        <div class="itemWithIcon illust-info">
          <div class="illust-info-author">ISUUED BY {{ illust.author }}</div>
          <img
            src="{% static 'media/generalLib.jpeg' %}"
            class="illust-info-author-icon circleIcon"
          />
        </div>
      </div>

      <div class="newspaper_footer">
        <div class="newspaper_footer_action">
          <div class="comments itemWithIcon newspaper_footer_action_item">
            <a href="{% url 'gallery:illust_comment' illust.pk %}">
              <span class="material-symbols-outlined"> comment </span>
              Comments
            </a>
          </div>

          <!-- <div class="shares itemWithIcon newspaper_footer_action_item">
            <span class="material-symbols-outlined"> ios_share </span>

            Share
          </div> -->

          <div class="itemWithIcon copyUrl newspaper_footer_action_item">
            <span class="material-symbols-outlined"> link </span>

            Link
            <div class="copiedAlert">Copied</div>
          </div>
        </div>
      </div>

      <ul class="illust-comment-list">
        {% for comment in comments %} {% if comment.is_public %}
        <li class="illust-comment-list-item">
          <div class="illust-comment-list-item-date">
            {{ comment.created_at|date:"nS F, Y" }}
          </div>
          <div class="illust-comment-list-item-name">{{ comment.name }}</div>
          <div class="illust-comment-list-item-text">{{ comment.text }}</div>
        </li>
        {% endif %} {% endfor %}
      </ul>
    </div>

    <div class="doubleFrame_nav --stick">
      <div class="headlineWithLeftLine">Getting Started</div>
      <ul class="colList">
        <li class="colListItem">INSTALLATION</li>
        <li class="colListItem">CREATE APP</li>
        <li class="colListItem">fjaklf</li>
        <li class="colListItem">fjaklf</li>
      </ul>
    </div>
  </div>
</main>

{% endblock %}

gallery/templates/gallery/illust_list.html
{% extends "extends/base.html" %} {% load static %} {% block main %}

<main class="main">
  <div class="doubleFrame">
    <div class="doubleFrame_main">
      <div>
        <!-- {% if illust_search_form.cleaned_data.tags %}
        <p class="tags" id="select-tags">
          選択しているタグ: 
          {% for tag in illust_search_form.cleaned_data.tags %}
          <span class="tag" data-pk="{{ tag.pk }}">{{ tag.name }}</span>
          {% endfor %}
        </p>
        {% endif %} -->

        <form id="search-form" action="" method="GET">
          {{ illust_search_form.key_word }}
          <button type="submit" id="search-button">検索</button>
          <div class="inline-checkbox">{{ illust_search_form.tags }}</div>
        </form>
      </div>

      <ul class="illust-list">
        {% for illust in illusts %}
        <li class="illust-list-item">
          <div class="illust-list-item-illust">
            <img src="{{ illust.illust.url }}" alt="" />
          </div>

          <div class="illust-list-item-caption">{{ illust.caption }}</div>

          <ul class="illust-list-item-illust-tag-list">
            {% for illust_tag in illust.illust_tags.all %}
            <li class="illust-list-item-illust-tag-list-item">
              # {{ illust_tag }}
            </li>
            {% endfor %}
          </ul>

          <div class="illust-list-item-title">
            <a
              class="hoverableLink"
              href="{% url 'gallery:illust_detail' illust.pk %}"
              >{{ illust.title }}</a
            >
          </div>

          <div class="illust-list-item-author">By {{ illust.author }}</div>

          <div class="illust-list-item-description">
            {{ illust.description }}
          </div>
        </li>

        {% empty %}
        <div class="illust-list-item-title">
          イラストが見つかりませんでした。
        </div>
        {% endfor %}
      </ul>
    </div>

    <nav class="doubleFrame_nav">
      <ul class="illust-list">
        <li class="illust-item-list">
          <div class="illust-list-item-pick-up">Live Article</div>

          <div class="illust-list-item-title">
            <a class="hoverableLink" href="{% url 'pages:design_policy' %}">
              Website design policy published
            </a>
          </div>

          <div class="illust-list-item-author">By okmtyuta</div>

          <div class="illust-list-item-description">New Article!</div>
        </li>
      </ul>
    </nav>
  </div>
</main>

{% endblock %}