article/urls.py
from django.urls import path

from . import views

app_name = "article"

urlpatterns = [
    path('', views.article_list, name="article_list"),
    path('detail/<int:pk>/', views.article_detail, name="article_detail"),
]

articles/urls.py
from django.urls import path

from . import views

app_name = "articles"

urlpatterns = [
    path('', views.article_list, name="article_list"),
    path('detail/<int:pk>/', views.article_detail, name="article_detail"),
]

pages/urls.py
from django.urls import path

from . import views

app_name = "pages"

urlpatterns = [
    path('', views.top, name="top"),
    path('users/detail', views.user_detail, name="user_detail"),
    path('design_policy', views.DesignPolicy.as_view(), name="design_policy"),
    path('variable', views.variable, name="variable"),
]

article/models.py
from django.db import models
from django.utils import timezone


class ArticleTag(models.Model):
    name = models.CharField('タグ名', max_length=100)

    def __str__(self):
        if hasattr(self, 'illust_count'):
            return f'{self.name}({self.illust_count})'
        else:
            return self.name


class Article(models.Model):
    title = models.CharField('タイトル', max_length=100)
    thumbnail = models.ImageField(upload_to='uploads/%Y/%m/%d/')
    caption = models.CharField('Caption', max_length=120, default="")
    author = models.CharField(max_length=255)
    description = models.TextField(max_length=300)
    body = models.TextField()
    article_tags = models.ManyToManyField(ArticleTag, verbose_name='タグ', blank=True)
    is_public = models.BooleanField('Public Article?', default=True)
    is_picked_up = models.BooleanField('Picked up Article?', default=False)
    created_at = models.DateTimeField('Created at', default=timezone.now)
    updated_at = models.DateTimeField('Updated at', default=timezone.now)
    related_articles = models.ManyToManyField("self", verbose_name='関連記事', blank=True)

    def __str__(self):
        return self.title


class ArticleComment(models.Model):
    """記事に紐づくコメント"""
    name = models.CharField('名前', max_length=255, default='Anonymous')
    text = models.TextField('本文')
    target = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name='対象記事')
    is_public = models.BooleanField('Public Comment?', default=True)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.text[:20]

article/views.py
from django.shortcuts import render
from .models import Article

def article_list(request):
    template_name = "article/article_list.html"
    articles = Article.objects.all().order_by("-created_at")
    picked_up_articles = Article.objects.filter(is_picked_up=True).order_by("-created_at")

    context = {
        "articles": articles,
        "picked_up_articles": picked_up_articles,
    }
    return render(request, template_name, context)

def article_detail(request, pk):
    article = Article.objects.get(pk = pk)
    context = {
        "article": article,
        "twitter_card": article,
    }
    template_name = "article/article_detail.html"
    return render(request, template_name, context)

articles/views.py
from django.shortcuts import render
from .models import Article

def article_list(request):
    template_name = "articles/article_list.html"
    articles = Article.objects.all().order_by("-created_at")
    picked_up_articles = Article.objects.filter(is_picked_up=True).order_by("-created_at")

    context = {
        "articles": articles,
        "picked_up_articles": picked_up_articles,
    }
    return render(request, template_name, context)

def article_detail(request, pk):
    article = Article.objects.get(pk = pk)
    context = {
        "article": article,
        "twitter_card": article,
    }
    template_name = "articles/article_detail.html"
    return render(request, template_name, context)

article/templates/article/article_detail.html
{% extends "extends/base.html" %} {% load static %} {% block main %}

<main class="main">
  <div class="singleFrame">
    <div class="article">
      <div class="article-title">{{ article.title }}</div>

      <div class="article-author">By {{ article.author }}</div>

      <div class="article-postedAt">
        Posted at {{ article.created_at|date:"nS F, Y" }}
      </div>

      <div class="article-body">
        {% autoescape off %} {{ article.body }} {% endautoescape %}
      </div>

      <div class="itemWithIcon illust-info">
        <div class="illust-info-author">ISUUED BY {{ illust.author }}</div>
        <img
          src="{% static 'media/generalLib.jpeg' %}"
          class="illust-info-author-icon circleIcon"
        />
      </div>



      <!-- <div class="paper updateLogs">
          <div class="paper_headline">
            HEADLINE
          </div>
  
          <ul class="itemization">
  
            <li class="itemization-item">
              <div class="itemization-item_heading">
                TODAY
              </div>
              created...
            </li>
            <li class="itemization-item">
              <div class="itemization-item_heading">
                TODAY
              </div>
              created...
            </li>
            <li class="itemization-item">
              <div class="itemization-item_heading">
                TODAY
              </div>
              created...
            </li>
            <li class="itemization-item">
              <div class="itemization-item_heading">
                TODAY
              </div>
              created...
            </li>
            <li class="itemization-item">
              <div class="itemization-item_heading">
                TODAY
              </div>
              created...
            </li>
  
          </ul>
        </div> -->

    </div>

    <div class="headlineSerif">
      関連記事
    </div>
    <ul class="related-article-list">
      {% for related_article in article.related_articles.all %}

      <li class="related-article-list-item">

        <div class="related-article-list-item-title">
          <a
            class="hoverableLink"
            href="{% url 'article:article_detail' article.pk %}"
          >
            {{ related_article.title }}
          </a>
        </div>
        <div class="related-article-list-item-description">

            {{ related_article.description }}
        </div>

      </li>

      {% empty %}
        <div class="article-list-item-title">No Article was posted</div>
      {% endfor %}
    </ul>
  </div>
</main>

{% endblock %}

article/templates/article/article_list.html
{% extends "extends/base.html" %} {% load static %} {% block main %}

<main class="main">
  <div class="tripleFrame">
    <aside class="tripleFrame_aside">

      <div>
        <ul class="article-list">
          {% for picked_up_article in picked_up_articles %}
          <li class="article-list-item">
            <div class="article-list-item-title">
              <a
                class="hoverableLink"
                href="{% url 'pages:article_detail' picked_up_article.pk %}"
                >{{ picked_up_article.title }}</a
              >
            </div>

            <div class="article-list-item-author">
              By {{ picked_up_article.author }}
            </div>

            <div class="article-list-item-description">
              {{ picked_up_article.description }}
            </div>
          </li>

          {% empty %}

          <div class="article-list-item-title">No Article was picked up</div>

          {% endfor %}
        </ul>
      </div>
    </aside>

    <div class="tripleFrame_main">
      <ul class="article-list">
        {% for article in articles %}
        <li class="article-list-item">
          <div class="article-list-item-thumbnail">
            <img src="{{ article.thumbnail.url }}" alt="" />
          </div>

          <div class="article-list-item-caption">{{ article.caption }}</div>

          <div class="article-list-item-title">
            <a
              class="hoverableLink"
              href="{% url 'article:article_detail' article.pk %}"
              >{{ article.title }}</a
            >
          </div>

          <div class="article-ist-item-author">By {{ article.author }}</div>

          <div class="article-list-item-description">
            {{ article.description }}
          </div>
        </li>

        {% empty %}
        <div class="article-list-item-title">No Article was posted</div>
        {% endfor %}
      </ul>
    </div>

    <nav class="tripleFrame_nav">
      <ul class="article-list">
        <li class="article-list-item">
          <div class="article-list-item-pick-up">Live Article</div>

          <div class="article-list-item-title">
            Website design policy published
          </div>

          <div class="article-list-item-author">By okmtyuta</div>

          <div class="article-list-item-description">
            Website design policy published.
          </div>
        </li>
      </ul>
    </nav>
  </div>
</main>

{% endblock %}